trigger: none

jobs:
- template: templates/linux-ci.yml
  parameters:
    AgentPool : 'Linux-Single-GPU-V100'
    JobName: 'Onnxruntime_Linux_GPU_Training'
    SubmoduleCheckoutMode: 'recursive'
    RunDockerBuildArgs: >
      -o ubuntu18.04 -d gpu -r $(Build.BinariesDirectory)
      -t onnxruntime_orttraining_ortmodule_tests_image
      -x "
      --enable_training
      --config $(buildConfig)
      --build_wheel
      --enable_nvtx_profile
      --skip_tests
      "
    DoNugetPack: 'false'
    RunORTModulePipeline: 'true'
    ORTModulePipeline: 'orttraining-linux-gpu-ortmodule-test-ci-pipeline.yml'
    DockerImageTag: 'onnxruntime_orttraining_ortmodule_tests_image'
    ArtifactName: 'drop-linux'
    TimeoutInMinutes: 120
    # Enable unreleased onnx opsets in CI builds
    # This facilitates testing the implementation for the new opsets
    AllowReleasedOpsetOnly: '0'
    Strategy: 
      maxParallel: 2
      matrix:
        Debug:
          buildConfig: Debug
        Release:
          buildConfig: Release

